### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by tbillion** [KrisKasprzak/FontConvert#1]
???
![Screenshot 2022-08-19 at 17-12-34 (no subject) - fatboi1942 gmail com - Gmail](https://user-images.githubusercontent.com/16172731/185713880-0f2e38ca-1800-4402-9625-6b7d70daaf85.png)

**Comment by KrisKasprzak** [comment]
What virus checker inversion are you using? Mine shows there are no viruses

**Comment by tbillion** [comment]
It's the one built in to gmail

**Comment by KrisKasprzak** [comment]
I've tested this file and it does not have a virus. I suspect your checker flags anything with and exe or dll. I have uploaded the files separately, try downloading them separately.
